chronosphereio/calyptia-go-fluentbit-config

parser.go, parser_test.go
Add an index to the name for inputs, filters, outputs, parsers and custom entries.
Add an index which is unique to each of filters, outputs, parsers and custom
sections to reproduce the behavior of fluent-bit and allow multiple
definitions for each plugin. This is related to problems I saw when the
duplicate port bug occured.
=> Add Index to Names

parser.go, parser_test.go
This PR fixes #6. It also fixes a bunch of other bugs which were being spackled over. This new parser should be able to handle and parse more of the fluent-bit pseudo-INI syntax.
Because it now fails to ignore hard parts of the syntax it might actually fail now in places where before it did not. It should not be hard to handle those new cases now though.
=> Support multiple values in a field

parser.go, parser_test.go
I added support for JSON based on the YAML parser. It uses the following format:
```json
{
"service": {
"flush_interval": 1,
"log_level": "error"
},
"pipeline": {
"inputs": [
{
"dummy": {
"name": "dummy",
"rate": 5
}
},
{
"dummy": {
"dummy": "{\"FOO\": \"BAR\"}",
"name": "dummy",
"rate": 1
}
}
],
"filters": [
{
"record_modifier": {
"match": "*",
"name": "record_modifier",
"record": "powered_by calyptia"
}
}
],
"outputs": [
{
"stdout": {
"match": "*",
"name": "stdout"
}
},
{
"exit": {
"flush_count": 10,
"match": "*",
"name": "exit"
}
}
]
}
}
```
Since the code is shared I also generalized the transformation between the shared grammar struct into receiver functions.
=> Support for JSON intermediary format

parser.go, parser_test.go
Add all the missing formats that strptime supports, including %E* a %O* format specifiers. 
Also added the %L specifier that mongodb uses but is not documented as supported by strptime:  https://linux.die.net/man/3/strptime.
This might actually be an unsupported format specifier.
=> parser: add missing format specifiers from strptime.

parser.go, parser_test.go, tests/ini-to-json/13-service.ini, tests/ini-to-json/13-service.json, tests/ini-to-json/14-api.ini, tests/ini-to-json/14-api.json, tests/ini-to-json/15-include.ini, tests/ini-to-json/15-include.json
More gracefully handle small configuration snippets, like:
invalid:
```ini
new-configuration
```
valid, but short:
```
@set var = val
```
or:
```
@include foobar.conf
```
I also added a simple test for includes as well as other syntax.
=> Handle small snippet configuration syntax

parser.go, parser_test.go
Add a UUID as a valid expression identifier.
This fixes the second case reported in https://github.com/calyptia/core/issues/157
Signed-off-by: Jorge Niedbalski <j@calyptia.com>
=> Add UUID as a expression identifier.

validator.go, validator_test.go
Quick fix for actually valid size.
Size as string was not validated to check if its string value is a number.
Closes https://github.com/calyptia/go-fluentbit-config/issues/32
=> fix valid size

parser.go, parser_test.go
Address type isn't converted on the Value() method to string by default.
It is also missing validation tests, added on this patch.
Signed-off-by: Jorge Niedbalski <j@calyptia.com>
=> Fix address type conversion to string.

parser.go, parser_test.go, validator.go
- To avoid duplicate the format/switch logic over different places lets add a dumpAs method to the configuration
type.
Signed-off-by: Jorge Niedbalski <j@calyptia.com>
=> Add DumpAs helper method to config.

parser.go, tests/ini-to-json/17-json-object.ini, tests/ini-to-json/17-json-object.json
When dumping INI format, json objects were ignored, causing for the value of the entry to be discarded.
This patch fixes that and adds a test to ensure parsing back and forth works correctly.
This is patch 1/2 to fix the issue related to https://github.com/calyptia/cloud/issues/632 reported by @eduardo
Signed-off-by: Jorge Niedbalski <j@calyptia.com>
=> Fix json object output for INI.

schema.go, validator_test.go
Adding missing options to the `http_loader` input plugin schema.
- `wait`
- `retry`
- `max_retries`
- `stop`
=> add missing options to http_loader schema

go.mod, go.sum, validator.go, validator_test.go
See [shortcut task](https://app.shortcut.com/chronosphere/story/95199/incorrect-rendering-of-map-values-in-the-ui-for-splunk-http-output-plugins).
=> validator: allow array in space and command delimited strings

property/property.go, property/property_test.go
Use `reflect.DeepEqual` to compare `any` instead of `==` that can cause a runtime panic:
```
runtime error: comparing uncomparable type []interface {}
```
[sc-102789]
=> property: fix panic in equality check of property value

config_test.go
In a follow up to #104 I have added tests that will run `.Validate()` on all our test data. This hopefully will also help catch similar errors.
=> tests: run validate on testdata.

validator.go, validator_test.go
Ignore properties starting with `core.` in validator.
[sc-87973]
=> ignore core. properties in validator

schema.go, service_port.go, service_port_test.go
Added new options for digest auth in `http_loader`.
And added new `cloudflare` input plugin schema.
[sc-107483]
=> feat: add support for auth digest in http_loader and added cloudflare schema [sc-107483]

schema.go
Adding missing option `aws_sqs_enable_imds` from `s3_sqs` Go input plugin schema.
See https://github.com/chronosphereio/calyptia-core-fluent-bit/pull/360
[sc-113551]
=> fix: add missing option aws_sqs_enable_imds from s3_sqs schema [sc-113551]

service_port.go, service_port_test.go
Add `csphere_http` input plugin port detection.
This plugin is only available in core-fluent-bit offering. It's very similar to the `http` input plugin but has grpc added support. Its default port is `443` when not specified.
[sc-118080]
=> feat: add csphere_http port detection [sc-118080]

schema.go
Revert the clobbering from core-image-index, depends upon: https://github.com/chronosphereio/calyptia-core-index/pull/423. If it is not merged this will get clobbered again eventually.
=> fix: revert overwriting the embed for all the schema files.

classic.go, config.go, config_test.go, testdata/parser.json, testdata/parser.yaml
Parsers are currently defined under `pipeline`, which is invalid:
```
the pipeline component 'parsers' is not valid.
```
=> fix: Move parsers to top-level [sc-135865]

schema.go, validator_test.go
Also removes `bucket` since it isn't read in the plugin. 
In a future PR I plan to go through the rest of the go plugins and update schema.go as needed.
=> bug: Update azure-blob-input schema validation to match go plugin [sc-132735]

schema.go, schema_test.go, section.go, testdata/processors/calyptia_processor.json, testdata/processors/calyptia_processor.yaml, validator.go
Add the missing support for the calyptia processor in the schema using InjectLTSPlugins. This should allow for the correct validation of pipeline configurations used in the chronosphere pipelines.
=> feat: add support for the calyptia processor when validating schemas.
